package Master;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author putra
 */
import Transaksi.*;
import Master.*;
import Koneksi.Koneksi;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class carimesin extends javax.swing.JDialog {
    String header[]={"Kode Mesin","Nama Mesin","Harga"};
    Connection con;
    Statement st;
    Koneksi kon=new Koneksi();
    String query;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private DefaultTableModel tabMode;
    
    private carimesinclass datatable;
    
     
    public carimesinclass gettabledata(){
        return datatable;
    }
    
    public void setdatatable(carimesinclass datatable){
        this.datatable = datatable;
    }
    
    private void UpdateJTable(){
        try{
            con=kon.open();
            st=con.createStatement();
            query="select kd_mesin, nama_mesin, harga_satuan from tb_mesin order by nama_mesin asc";
            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                String a=rs.getString("kd_mesin");
                String b=rs.getString("nama_mesin");
                String c=rs.getString("harga_satuan");
                
                String data []={a,b,c};
                tabMode.addRow(data);
            }
        }catch(SQLException sqle){
           JOptionPane.showMessageDialog(null,"Failed show data! "+sqle);       
    }
}
    
    
    public carimesin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCariMesin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmesin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Mesin");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nama Mesin");

        txtCariMesin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMesinKeyReleased(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelmesin.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tabelmesin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabMode=new DefaultTableModel(null,header);
        tabelmesin.setModel(tabMode);
        tabelmesin.setToolTipText("");
        tabelmesin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelmesin.setPreferredSize(new java.awt.Dimension(650, 200));
        tabelmesin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmesinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmesin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariMesin))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCariMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Connection con;
        Statement st;
        Koneksi kon=new Koneksi();
        UpdateJTable();
        txtCariMesin.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtCariMesinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMesinKeyReleased
        // TODO add your handling code here:
        String temp = txtCariMesin.getText()+"%";
        String sql = "select kd_mesin, nama_mesin, harga_satuan from tb_mesin where nama_mesin like '"+ temp+"'";
        try{
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery(); 
           tabelmesin.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal! ");
        }
    }//GEN-LAST:event_txtCariMesinKeyReleased

    private void tabelmesinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmesinMouseClicked
        // TODO add your handling code here:
            datatable=new carimesinclass();
            TableModel data = tabelmesin.getModel();
            datatable.setid(data.getValueAt(tabelmesin.getSelectedRow(), 0).toString());
            datatable.setnama(data.getValueAt(tabelmesin.getSelectedRow(), 1).toString());
            datatable.setharga(data.getValueAt(tabelmesin.getSelectedRow(), 2).toString());
            this.setVisible(false);
    }//GEN-LAST:event_tabelmesinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carimesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carimesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carimesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carimesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                carimesin dialog = new carimesin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelmesin;
    private javax.swing.JTextField txtCariMesin;
    // End of variables declaration//GEN-END:variables
}
